run:
  # which dirs to skip: they won't be analyzed;
  skip-dirs:
    - vendor
    - recipe/packs
    - launcher/buildpackapplifecycle

linters-settings:
  govet:
    # report about shadowed variables
    check-shadowing: true
  gocyclo:
    # minimal code complexity to report
    min-complexity: 10
  maligned:
    # print struct with more effective memory layout
    suggest-new: true
  lll:
    line-length: 512

linters:
  enable-all: true
  disable:
    - gochecknoglobals
    - scopelint
    - gochecknoinits
    - typecheck
    - goconst

issues:
  exclude-use-default: true
  exclude:
      - G402  # Temporarily do not look for bad TLS connection settings.

  # Maximum issues count per one linter. Set to 0 to disable.
  max-per-linter: 0

  # Maximum count of issues with the same text. Set to 0 to disable
  max-same: 0

  # Show only new issues
  new: false
