apiVersion: skaffold/v2beta7
kind: Config
metadata:
  name: eirini
build:
  local:
    concurrency: 4
  artifacts:
  - image: eirini/opi
    custom:
      buildCommand: ./scripts/build opi
      dependencies:
        command: ./scripts/deps opi
  - image: eirini/route-collector
    custom:
      buildCommand: ./scripts/build route-collector
      dependencies:
        command: ./scripts/deps route-collector
  - image: eirini/eirini-controller
    custom:
      buildCommand: ./scripts/build eirini-controller
      dependencies:
        command: ./scripts/deps eirini-controller
  - image: eirini/event-reporter
    custom:
      buildCommand: ./scripts/build event-reporter
      dependencies:
        command: ./scripts/deps event-reporter
  - image: eirini/instance-index-env-injector
    custom:
      buildCommand: ./scripts/build instance-index-env-injector
      dependencies:
        command: ./scripts/deps instance-index-env-injector
  - image: eirini/metrics-collector
    custom:
      buildCommand: ./scripts/build metrics-collector
      dependencies:
        command: ./scripts/deps metrics-collector
  - image: eirini/route-pod-informer
    custom:
      buildCommand: ./scripts/build route-pod-informer
      dependencies:
        command: ./scripts/deps route-pod-informer
  - image: eirini/route-statefulset-informer
    custom:
      buildCommand: ./scripts/build route-statefulset-informer
      dependencies:
        command: ./scripts/deps route-statefulset-informer
  - image: eirini/task-reporter
    custom:
      buildCommand: ./scripts/build task-reporter
      dependencies:
        command: ./scripts/deps task-reporter
# Deployment steps are defined in the profiles below. In order to
# run a profile do ./scripts/skaffold run -p <profile-name>
# The reason why there is no default deployment is that our deployment
# differ way too much
deploy:
profiles:
- name: helmless-single
  deploy:
    kubectl:
      manifests:
      - ../eirini-release/deploy/core/*.yml
      - ../eirini-release/deploy/core/single-namespace/*.yml
      - ../eirini-release/deploy/events/*.yml
      - ../eirini-release/deploy/events/single-namespace/*.yml
      - ../eirini-release/deploy/metrics/*.yml
      - ../eirini-release/deploy/metrics/single-namespace/*.yml
      - ../eirini-release/deploy/workloads/*.yml
      - ../eirini-release/deploy/testing/cc-wiremock/*.yml
- name: helmless-multi
  deploy:
    kubectl:
      manifests:
      - ../eirini-release/deploy/core/*.yml
      - ../eirini-release/deploy/core/multi-namespace/*.yml
      - ../eirini-release/deploy/events/*.yml
      - ../eirini-release/deploy/events/multi-namespace/*.yml
      - ../eirini-release/deploy/metrics/*.yml
      - ../eirini-release/deploy/metrics/multi-namespace/*.yml
      - ../eirini-release/deploy/workloads/*.yml
      - ../eirini-release/deploy/testing/cc-wiremock/*.yml
# Warning: this profile should only be used for helmless deletion. It is
# useful if you are trying to delete a helmless deployment but are unsure
# how it was deployed
- name: helmless
  deploy:
    kubectl:
      manifests:
      - ../eirini-release/deploy/**/*.yml
      - ../eirini-release/deploy/**/**/*.yml
- name: helm
  deploy:
    kubectl:
      manifests:
      - ../eirini-release/deploy/testing/cc-wiremock/*.yml
    helm:
      releases:
      - name: nats
        remote: true
        chartPath: bitnami/nats
        namespace: eirini-core
        setValueTemplates:
          auth.user: nats
          auth.password: "{{.NATS_PASSWORD}}"
      - name: eirini
        chartPath: ../eirini-release/helm/eirini
        namespace: eirini-core
        valuesFiles:
        - ../eirini-release/helm/scripts/assets/helm-values-template.yml
        setValueTemplates:
          kube.external_ips[0]: "{{.CLUSTER_IP}}"
          opi.enable_multi_namespace_support: "{{.HELM_ENABLE_MULTI_NS}}"
        artifactOverrides:
          opi.image: eirini/opi
          opi.route_collector_image: eirini/route-collector
          opi.eirini_controller_image: eirini/eirini-controller
          opi.event_reporter_image: eirini/event-reporter
          opi.metrics_collector_image: eirini/metrics-collector
          opi.route_statefulset_informer_image: eirini/route-statefulset-informer
          opi.route_pod_informer_image: eirini/route-pod-informer
          opi.task_reporter_image: eirini/task-reporter
          instanceIndexEnvInjector.image: eirini/instance-index-env-injector
