// Code generated by counterfeiter. DO NOT EDIT.
package routefakes

import (
	"sync"

	"code.cloudfoundry.org/eirini"
	"code.cloudfoundry.org/eirini/route"
)

type FakeLister struct {
	ListRoutesStub        func() ([]*eirini.Routes, error)
	listRoutesMutex       sync.RWMutex
	listRoutesArgsForCall []struct{}
	listRoutesReturns     struct {
		result1 []*eirini.Routes
		result2 error
	}
	listRoutesReturnsOnCall map[int]struct {
		result1 []*eirini.Routes
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeLister) ListRoutes() ([]*eirini.Routes, error) {
	fake.listRoutesMutex.Lock()
	ret, specificReturn := fake.listRoutesReturnsOnCall[len(fake.listRoutesArgsForCall)]
	fake.listRoutesArgsForCall = append(fake.listRoutesArgsForCall, struct{}{})
	fake.recordInvocation("ListRoutes", []interface{}{})
	fake.listRoutesMutex.Unlock()
	if fake.ListRoutesStub != nil {
		return fake.ListRoutesStub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.listRoutesReturns.result1, fake.listRoutesReturns.result2
}

func (fake *FakeLister) ListRoutesCallCount() int {
	fake.listRoutesMutex.RLock()
	defer fake.listRoutesMutex.RUnlock()
	return len(fake.listRoutesArgsForCall)
}

func (fake *FakeLister) ListRoutesReturns(result1 []*eirini.Routes, result2 error) {
	fake.ListRoutesStub = nil
	fake.listRoutesReturns = struct {
		result1 []*eirini.Routes
		result2 error
	}{result1, result2}
}

func (fake *FakeLister) ListRoutesReturnsOnCall(i int, result1 []*eirini.Routes, result2 error) {
	fake.ListRoutesStub = nil
	if fake.listRoutesReturnsOnCall == nil {
		fake.listRoutesReturnsOnCall = make(map[int]struct {
			result1 []*eirini.Routes
			result2 error
		})
	}
	fake.listRoutesReturnsOnCall[i] = struct {
		result1 []*eirini.Routes
		result2 error
	}{result1, result2}
}

func (fake *FakeLister) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.listRoutesMutex.RLock()
	defer fake.listRoutesMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeLister) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ route.Lister = new(FakeLister)
