// Code generated by counterfeiter. DO NOT EDIT.
package routefakes

import (
	"context"
	"sync"

	"code.cloudfoundry.org/eirini/k8s/informers/route"
	v1 "k8s.io/api/core/v1"
)

type FakePodUpdateEventHandler struct {
	HandleStub        func(context.Context, *v1.Pod, *v1.Pod)
	handleMutex       sync.RWMutex
	handleArgsForCall []struct {
		arg1 context.Context
		arg2 *v1.Pod
		arg3 *v1.Pod
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakePodUpdateEventHandler) Handle(arg1 context.Context, arg2 *v1.Pod, arg3 *v1.Pod) {
	fake.handleMutex.Lock()
	fake.handleArgsForCall = append(fake.handleArgsForCall, struct {
		arg1 context.Context
		arg2 *v1.Pod
		arg3 *v1.Pod
	}{arg1, arg2, arg3})
	stub := fake.HandleStub
	fake.recordInvocation("Handle", []interface{}{arg1, arg2, arg3})
	fake.handleMutex.Unlock()
	if stub != nil {
		fake.HandleStub(arg1, arg2, arg3)
	}
}

func (fake *FakePodUpdateEventHandler) HandleCallCount() int {
	fake.handleMutex.RLock()
	defer fake.handleMutex.RUnlock()
	return len(fake.handleArgsForCall)
}

func (fake *FakePodUpdateEventHandler) HandleCalls(stub func(context.Context, *v1.Pod, *v1.Pod)) {
	fake.handleMutex.Lock()
	defer fake.handleMutex.Unlock()
	fake.HandleStub = stub
}

func (fake *FakePodUpdateEventHandler) HandleArgsForCall(i int) (context.Context, *v1.Pod, *v1.Pod) {
	fake.handleMutex.RLock()
	defer fake.handleMutex.RUnlock()
	argsForCall := fake.handleArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakePodUpdateEventHandler) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.handleMutex.RLock()
	defer fake.handleMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakePodUpdateEventHandler) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ route.PodUpdateEventHandler = new(FakePodUpdateEventHandler)
