// Code generated by counterfeiter. DO NOT EDIT.
package routefakes

import (
	"sync"

	"code.cloudfoundry.org/eirini/k8s/informers/route"
	v1 "k8s.io/api/apps/v1"
)

type FakeStatefulSetDeleteEventHandler struct {
	HandleStub        func(*v1.StatefulSet)
	handleMutex       sync.RWMutex
	handleArgsForCall []struct {
		arg1 *v1.StatefulSet
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeStatefulSetDeleteEventHandler) Handle(arg1 *v1.StatefulSet) {
	fake.handleMutex.Lock()
	fake.handleArgsForCall = append(fake.handleArgsForCall, struct {
		arg1 *v1.StatefulSet
	}{arg1})
	fake.recordInvocation("Handle", []interface{}{arg1})
	fake.handleMutex.Unlock()
	if fake.HandleStub != nil {
		fake.HandleStub(arg1)
	}
}

func (fake *FakeStatefulSetDeleteEventHandler) HandleCallCount() int {
	fake.handleMutex.RLock()
	defer fake.handleMutex.RUnlock()
	return len(fake.handleArgsForCall)
}

func (fake *FakeStatefulSetDeleteEventHandler) HandleCalls(stub func(*v1.StatefulSet)) {
	fake.handleMutex.Lock()
	defer fake.handleMutex.Unlock()
	fake.HandleStub = stub
}

func (fake *FakeStatefulSetDeleteEventHandler) HandleArgsForCall(i int) *v1.StatefulSet {
	fake.handleMutex.RLock()
	defer fake.handleMutex.RUnlock()
	argsForCall := fake.handleArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeStatefulSetDeleteEventHandler) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.handleMutex.RLock()
	defer fake.handleMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeStatefulSetDeleteEventHandler) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ route.StatefulSetDeleteEventHandler = new(FakeStatefulSetDeleteEventHandler)
