// Code generated by counterfeiter. DO NOT EDIT.
package waitfakes

import (
	"sync"

	"code.cloudfoundry.org/eirini/rootfspatcher/wait"
	apicore "k8s.io/api/core/v1"
	meta "k8s.io/apimachinery/pkg/apis/meta/v1"
)

type FakePodLister struct {
	ListStub        func(opts meta.ListOptions) (*apicore.PodList, error)
	listMutex       sync.RWMutex
	listArgsForCall []struct {
		opts meta.ListOptions
	}
	listReturns struct {
		result1 *apicore.PodList
		result2 error
	}
	listReturnsOnCall map[int]struct {
		result1 *apicore.PodList
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakePodLister) List(opts meta.ListOptions) (*apicore.PodList, error) {
	fake.listMutex.Lock()
	ret, specificReturn := fake.listReturnsOnCall[len(fake.listArgsForCall)]
	fake.listArgsForCall = append(fake.listArgsForCall, struct {
		opts meta.ListOptions
	}{opts})
	fake.recordInvocation("List", []interface{}{opts})
	fake.listMutex.Unlock()
	if fake.ListStub != nil {
		return fake.ListStub(opts)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.listReturns.result1, fake.listReturns.result2
}

func (fake *FakePodLister) ListCallCount() int {
	fake.listMutex.RLock()
	defer fake.listMutex.RUnlock()
	return len(fake.listArgsForCall)
}

func (fake *FakePodLister) ListArgsForCall(i int) meta.ListOptions {
	fake.listMutex.RLock()
	defer fake.listMutex.RUnlock()
	return fake.listArgsForCall[i].opts
}

func (fake *FakePodLister) ListReturns(result1 *apicore.PodList, result2 error) {
	fake.ListStub = nil
	fake.listReturns = struct {
		result1 *apicore.PodList
		result2 error
	}{result1, result2}
}

func (fake *FakePodLister) ListReturnsOnCall(i int, result1 *apicore.PodList, result2 error) {
	fake.ListStub = nil
	if fake.listReturnsOnCall == nil {
		fake.listReturnsOnCall = make(map[int]struct {
			result1 *apicore.PodList
			result2 error
		})
	}
	fake.listReturnsOnCall[i] = struct {
		result1 *apicore.PodList
		result2 error
	}{result1, result2}
}

func (fake *FakePodLister) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.listMutex.RLock()
	defer fake.listMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakePodLister) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ wait.PodLister = new(FakePodLister)
