// Code generated by counterfeiter. DO NOT EDIT.
package jobsfakes

import (
	"sync"

	"code.cloudfoundry.org/eirini/k8s/jobs"
	"code.cloudfoundry.org/eirini/opi"
	v1 "k8s.io/api/batch/v1"
)

type FakeTaskToJob struct {
	Stub        func(*opi.Task) *v1.Job
	mutex       sync.RWMutex
	argsForCall []struct {
		arg1 *opi.Task
	}
	returns struct {
		result1 *v1.Job
	}
	returnsOnCall map[int]struct {
		result1 *v1.Job
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeTaskToJob) Spy(arg1 *opi.Task) *v1.Job {
	fake.mutex.Lock()
	ret, specificReturn := fake.returnsOnCall[len(fake.argsForCall)]
	fake.argsForCall = append(fake.argsForCall, struct {
		arg1 *opi.Task
	}{arg1})
	stub := fake.Stub
	returns := fake.returns
	fake.recordInvocation("TaskToJob", []interface{}{arg1})
	fake.mutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return returns.result1
}

func (fake *FakeTaskToJob) CallCount() int {
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	return len(fake.argsForCall)
}

func (fake *FakeTaskToJob) Calls(stub func(*opi.Task) *v1.Job) {
	fake.mutex.Lock()
	defer fake.mutex.Unlock()
	fake.Stub = stub
}

func (fake *FakeTaskToJob) ArgsForCall(i int) *opi.Task {
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	return fake.argsForCall[i].arg1
}

func (fake *FakeTaskToJob) Returns(result1 *v1.Job) {
	fake.mutex.Lock()
	defer fake.mutex.Unlock()
	fake.Stub = nil
	fake.returns = struct {
		result1 *v1.Job
	}{result1}
}

func (fake *FakeTaskToJob) ReturnsOnCall(i int, result1 *v1.Job) {
	fake.mutex.Lock()
	defer fake.mutex.Unlock()
	fake.Stub = nil
	if fake.returnsOnCall == nil {
		fake.returnsOnCall = make(map[int]struct {
			result1 *v1.Job
		})
	}
	fake.returnsOnCall[i] = struct {
		result1 *v1.Job
	}{result1}
}

func (fake *FakeTaskToJob) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeTaskToJob) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ jobs.TaskToJob = new(FakeTaskToJob).Spy
