// Code generated by counterfeiter. DO NOT EDIT.
package bifrostfakes

import (
	"sync"

	"code.cloudfoundry.org/eirini/bifrost"
	"code.cloudfoundry.org/eirini/opi"
)

type FakeStagingDesirer struct {
	DeleteStub        func(string) error
	deleteMutex       sync.RWMutex
	deleteArgsForCall []struct {
		arg1 string
	}
	deleteReturns struct {
		result1 error
	}
	deleteReturnsOnCall map[int]struct {
		result1 error
	}
	DesireStagingStub        func(*opi.StagingTask) error
	desireStagingMutex       sync.RWMutex
	desireStagingArgsForCall []struct {
		arg1 *opi.StagingTask
	}
	desireStagingReturns struct {
		result1 error
	}
	desireStagingReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeStagingDesirer) Delete(arg1 string) error {
	fake.deleteMutex.Lock()
	ret, specificReturn := fake.deleteReturnsOnCall[len(fake.deleteArgsForCall)]
	fake.deleteArgsForCall = append(fake.deleteArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.recordInvocation("Delete", []interface{}{arg1})
	fake.deleteMutex.Unlock()
	if fake.DeleteStub != nil {
		return fake.DeleteStub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.deleteReturns
	return fakeReturns.result1
}

func (fake *FakeStagingDesirer) DeleteCallCount() int {
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	return len(fake.deleteArgsForCall)
}

func (fake *FakeStagingDesirer) DeleteCalls(stub func(string) error) {
	fake.deleteMutex.Lock()
	defer fake.deleteMutex.Unlock()
	fake.DeleteStub = stub
}

func (fake *FakeStagingDesirer) DeleteArgsForCall(i int) string {
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	argsForCall := fake.deleteArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeStagingDesirer) DeleteReturns(result1 error) {
	fake.deleteMutex.Lock()
	defer fake.deleteMutex.Unlock()
	fake.DeleteStub = nil
	fake.deleteReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeStagingDesirer) DeleteReturnsOnCall(i int, result1 error) {
	fake.deleteMutex.Lock()
	defer fake.deleteMutex.Unlock()
	fake.DeleteStub = nil
	if fake.deleteReturnsOnCall == nil {
		fake.deleteReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeStagingDesirer) DesireStaging(arg1 *opi.StagingTask) error {
	fake.desireStagingMutex.Lock()
	ret, specificReturn := fake.desireStagingReturnsOnCall[len(fake.desireStagingArgsForCall)]
	fake.desireStagingArgsForCall = append(fake.desireStagingArgsForCall, struct {
		arg1 *opi.StagingTask
	}{arg1})
	fake.recordInvocation("DesireStaging", []interface{}{arg1})
	fake.desireStagingMutex.Unlock()
	if fake.DesireStagingStub != nil {
		return fake.DesireStagingStub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.desireStagingReturns
	return fakeReturns.result1
}

func (fake *FakeStagingDesirer) DesireStagingCallCount() int {
	fake.desireStagingMutex.RLock()
	defer fake.desireStagingMutex.RUnlock()
	return len(fake.desireStagingArgsForCall)
}

func (fake *FakeStagingDesirer) DesireStagingCalls(stub func(*opi.StagingTask) error) {
	fake.desireStagingMutex.Lock()
	defer fake.desireStagingMutex.Unlock()
	fake.DesireStagingStub = stub
}

func (fake *FakeStagingDesirer) DesireStagingArgsForCall(i int) *opi.StagingTask {
	fake.desireStagingMutex.RLock()
	defer fake.desireStagingMutex.RUnlock()
	argsForCall := fake.desireStagingArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeStagingDesirer) DesireStagingReturns(result1 error) {
	fake.desireStagingMutex.Lock()
	defer fake.desireStagingMutex.Unlock()
	fake.DesireStagingStub = nil
	fake.desireStagingReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeStagingDesirer) DesireStagingReturnsOnCall(i int, result1 error) {
	fake.desireStagingMutex.Lock()
	defer fake.desireStagingMutex.Unlock()
	fake.DesireStagingStub = nil
	if fake.desireStagingReturnsOnCall == nil {
		fake.desireStagingReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.desireStagingReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeStagingDesirer) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	fake.desireStagingMutex.RLock()
	defer fake.desireStagingMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeStagingDesirer) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ bifrost.StagingDesirer = new(FakeStagingDesirer)
