// Code generated by counterfeiter. DO NOT EDIT.
package bifrostfakes

import (
	"sync"

	"code.cloudfoundry.org/eirini/bifrost"
)

type FakeStagingDeleter struct {
	DeleteStagingStub        func(string) error
	deleteStagingMutex       sync.RWMutex
	deleteStagingArgsForCall []struct {
		arg1 string
	}
	deleteStagingReturns struct {
		result1 error
	}
	deleteStagingReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeStagingDeleter) DeleteStaging(arg1 string) error {
	fake.deleteStagingMutex.Lock()
	ret, specificReturn := fake.deleteStagingReturnsOnCall[len(fake.deleteStagingArgsForCall)]
	fake.deleteStagingArgsForCall = append(fake.deleteStagingArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.DeleteStagingStub
	fakeReturns := fake.deleteStagingReturns
	fake.recordInvocation("DeleteStaging", []interface{}{arg1})
	fake.deleteStagingMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeStagingDeleter) DeleteStagingCallCount() int {
	fake.deleteStagingMutex.RLock()
	defer fake.deleteStagingMutex.RUnlock()
	return len(fake.deleteStagingArgsForCall)
}

func (fake *FakeStagingDeleter) DeleteStagingCalls(stub func(string) error) {
	fake.deleteStagingMutex.Lock()
	defer fake.deleteStagingMutex.Unlock()
	fake.DeleteStagingStub = stub
}

func (fake *FakeStagingDeleter) DeleteStagingArgsForCall(i int) string {
	fake.deleteStagingMutex.RLock()
	defer fake.deleteStagingMutex.RUnlock()
	argsForCall := fake.deleteStagingArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeStagingDeleter) DeleteStagingReturns(result1 error) {
	fake.deleteStagingMutex.Lock()
	defer fake.deleteStagingMutex.Unlock()
	fake.DeleteStagingStub = nil
	fake.deleteStagingReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeStagingDeleter) DeleteStagingReturnsOnCall(i int, result1 error) {
	fake.deleteStagingMutex.Lock()
	defer fake.deleteStagingMutex.Unlock()
	fake.DeleteStagingStub = nil
	if fake.deleteStagingReturnsOnCall == nil {
		fake.deleteStagingReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteStagingReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeStagingDeleter) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.deleteStagingMutex.RLock()
	defer fake.deleteStagingMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeStagingDeleter) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ bifrost.StagingDeleter = new(FakeStagingDeleter)
