// Code generated by counterfeiter. DO NOT EDIT.
package bifrostfakes

import (
	"sync"

	"code.cloudfoundry.org/eirini/bifrost"
	"code.cloudfoundry.org/eirini/opi"
)

type FakeStagingDesirer struct {
	DeleteStagingStub        func(string) error
	deleteStagingMutex       sync.RWMutex
	deleteStagingArgsForCall []struct {
		arg1 string
	}
	deleteStagingReturns struct {
		result1 error
	}
	deleteStagingReturnsOnCall map[int]struct {
		result1 error
	}
	DesireStagingStub        func(*opi.StagingTask) error
	desireStagingMutex       sync.RWMutex
	desireStagingArgsForCall []struct {
		arg1 *opi.StagingTask
	}
	desireStagingReturns struct {
		result1 error
	}
	desireStagingReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeStagingDesirer) DeleteStaging(arg1 string) error {
	fake.deleteStagingMutex.Lock()
	ret, specificReturn := fake.deleteStagingReturnsOnCall[len(fake.deleteStagingArgsForCall)]
	fake.deleteStagingArgsForCall = append(fake.deleteStagingArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.recordInvocation("DeleteStaging", []interface{}{arg1})
	fake.deleteStagingMutex.Unlock()
	if fake.DeleteStagingStub != nil {
		return fake.DeleteStagingStub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.deleteStagingReturns
	return fakeReturns.result1
}

func (fake *FakeStagingDesirer) DeleteStagingCallCount() int {
	fake.deleteStagingMutex.RLock()
	defer fake.deleteStagingMutex.RUnlock()
	return len(fake.deleteStagingArgsForCall)
}

func (fake *FakeStagingDesirer) DeleteStagingCalls(stub func(string) error) {
	fake.deleteStagingMutex.Lock()
	defer fake.deleteStagingMutex.Unlock()
	fake.DeleteStagingStub = stub
}

func (fake *FakeStagingDesirer) DeleteStagingArgsForCall(i int) string {
	fake.deleteStagingMutex.RLock()
	defer fake.deleteStagingMutex.RUnlock()
	argsForCall := fake.deleteStagingArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeStagingDesirer) DeleteStagingReturns(result1 error) {
	fake.deleteStagingMutex.Lock()
	defer fake.deleteStagingMutex.Unlock()
	fake.DeleteStagingStub = nil
	fake.deleteStagingReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeStagingDesirer) DeleteStagingReturnsOnCall(i int, result1 error) {
	fake.deleteStagingMutex.Lock()
	defer fake.deleteStagingMutex.Unlock()
	fake.DeleteStagingStub = nil
	if fake.deleteStagingReturnsOnCall == nil {
		fake.deleteStagingReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteStagingReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeStagingDesirer) DesireStaging(arg1 *opi.StagingTask) error {
	fake.desireStagingMutex.Lock()
	ret, specificReturn := fake.desireStagingReturnsOnCall[len(fake.desireStagingArgsForCall)]
	fake.desireStagingArgsForCall = append(fake.desireStagingArgsForCall, struct {
		arg1 *opi.StagingTask
	}{arg1})
	fake.recordInvocation("DesireStaging", []interface{}{arg1})
	fake.desireStagingMutex.Unlock()
	if fake.DesireStagingStub != nil {
		return fake.DesireStagingStub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.desireStagingReturns
	return fakeReturns.result1
}

func (fake *FakeStagingDesirer) DesireStagingCallCount() int {
	fake.desireStagingMutex.RLock()
	defer fake.desireStagingMutex.RUnlock()
	return len(fake.desireStagingArgsForCall)
}

func (fake *FakeStagingDesirer) DesireStagingCalls(stub func(*opi.StagingTask) error) {
	fake.desireStagingMutex.Lock()
	defer fake.desireStagingMutex.Unlock()
	fake.DesireStagingStub = stub
}

func (fake *FakeStagingDesirer) DesireStagingArgsForCall(i int) *opi.StagingTask {
	fake.desireStagingMutex.RLock()
	defer fake.desireStagingMutex.RUnlock()
	argsForCall := fake.desireStagingArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeStagingDesirer) DesireStagingReturns(result1 error) {
	fake.desireStagingMutex.Lock()
	defer fake.desireStagingMutex.Unlock()
	fake.DesireStagingStub = nil
	fake.desireStagingReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeStagingDesirer) DesireStagingReturnsOnCall(i int, result1 error) {
	fake.desireStagingMutex.Lock()
	defer fake.desireStagingMutex.Unlock()
	fake.DesireStagingStub = nil
	if fake.desireStagingReturnsOnCall == nil {
		fake.desireStagingReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.desireStagingReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeStagingDesirer) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.deleteStagingMutex.RLock()
	defer fake.deleteStagingMutex.RUnlock()
	fake.desireStagingMutex.RLock()
	defer fake.desireStagingMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeStagingDesirer) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ bifrost.StagingDesirer = new(FakeStagingDesirer)
