// Code generated by counterfeiter. DO NOT EDIT.
package handlerfakes

import (
	"context"
	"sync"

	"code.cloudfoundry.org/eirini/handler"
	"code.cloudfoundry.org/eirini/models/cf"
)

type FakeTaskBifrost struct {
	CompleteTaskStub        func(string) error
	completeTaskMutex       sync.RWMutex
	completeTaskArgsForCall []struct {
		arg1 string
	}
	completeTaskReturns struct {
		result1 error
	}
	completeTaskReturnsOnCall map[int]struct {
		result1 error
	}
	TransferTaskStub        func(context.Context, string, cf.TaskRequest) error
	transferTaskMutex       sync.RWMutex
	transferTaskArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 cf.TaskRequest
	}
	transferTaskReturns struct {
		result1 error
	}
	transferTaskReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeTaskBifrost) CompleteTask(arg1 string) error {
	fake.completeTaskMutex.Lock()
	ret, specificReturn := fake.completeTaskReturnsOnCall[len(fake.completeTaskArgsForCall)]
	fake.completeTaskArgsForCall = append(fake.completeTaskArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.recordInvocation("CompleteTask", []interface{}{arg1})
	fake.completeTaskMutex.Unlock()
	if fake.CompleteTaskStub != nil {
		return fake.CompleteTaskStub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.completeTaskReturns
	return fakeReturns.result1
}

func (fake *FakeTaskBifrost) CompleteTaskCallCount() int {
	fake.completeTaskMutex.RLock()
	defer fake.completeTaskMutex.RUnlock()
	return len(fake.completeTaskArgsForCall)
}

func (fake *FakeTaskBifrost) CompleteTaskCalls(stub func(string) error) {
	fake.completeTaskMutex.Lock()
	defer fake.completeTaskMutex.Unlock()
	fake.CompleteTaskStub = stub
}

func (fake *FakeTaskBifrost) CompleteTaskArgsForCall(i int) string {
	fake.completeTaskMutex.RLock()
	defer fake.completeTaskMutex.RUnlock()
	argsForCall := fake.completeTaskArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeTaskBifrost) CompleteTaskReturns(result1 error) {
	fake.completeTaskMutex.Lock()
	defer fake.completeTaskMutex.Unlock()
	fake.CompleteTaskStub = nil
	fake.completeTaskReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeTaskBifrost) CompleteTaskReturnsOnCall(i int, result1 error) {
	fake.completeTaskMutex.Lock()
	defer fake.completeTaskMutex.Unlock()
	fake.CompleteTaskStub = nil
	if fake.completeTaskReturnsOnCall == nil {
		fake.completeTaskReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.completeTaskReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeTaskBifrost) TransferTask(arg1 context.Context, arg2 string, arg3 cf.TaskRequest) error {
	fake.transferTaskMutex.Lock()
	ret, specificReturn := fake.transferTaskReturnsOnCall[len(fake.transferTaskArgsForCall)]
	fake.transferTaskArgsForCall = append(fake.transferTaskArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 cf.TaskRequest
	}{arg1, arg2, arg3})
	fake.recordInvocation("TransferTask", []interface{}{arg1, arg2, arg3})
	fake.transferTaskMutex.Unlock()
	if fake.TransferTaskStub != nil {
		return fake.TransferTaskStub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.transferTaskReturns
	return fakeReturns.result1
}

func (fake *FakeTaskBifrost) TransferTaskCallCount() int {
	fake.transferTaskMutex.RLock()
	defer fake.transferTaskMutex.RUnlock()
	return len(fake.transferTaskArgsForCall)
}

func (fake *FakeTaskBifrost) TransferTaskCalls(stub func(context.Context, string, cf.TaskRequest) error) {
	fake.transferTaskMutex.Lock()
	defer fake.transferTaskMutex.Unlock()
	fake.TransferTaskStub = stub
}

func (fake *FakeTaskBifrost) TransferTaskArgsForCall(i int) (context.Context, string, cf.TaskRequest) {
	fake.transferTaskMutex.RLock()
	defer fake.transferTaskMutex.RUnlock()
	argsForCall := fake.transferTaskArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeTaskBifrost) TransferTaskReturns(result1 error) {
	fake.transferTaskMutex.Lock()
	defer fake.transferTaskMutex.Unlock()
	fake.TransferTaskStub = nil
	fake.transferTaskReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeTaskBifrost) TransferTaskReturnsOnCall(i int, result1 error) {
	fake.transferTaskMutex.Lock()
	defer fake.transferTaskMutex.Unlock()
	fake.TransferTaskStub = nil
	if fake.transferTaskReturnsOnCall == nil {
		fake.transferTaskReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.transferTaskReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeTaskBifrost) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.completeTaskMutex.RLock()
	defer fake.completeTaskMutex.RUnlock()
	fake.transferTaskMutex.RLock()
	defer fake.transferTaskMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeTaskBifrost) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ handler.TaskBifrost = new(FakeTaskBifrost)
