FROM golang:1.12.2-stretch as builder
WORKDIR /go/src/code.cloudfoundry.org/eirini
COPY . .
RUN GOOS=linux go build -a -o /uploader ./recipe/cmd/uploader/uploader.go

FROM packs/cf

WORKDIR /workspace

RUN mkdir -p /packs

COPY --from=builder /uploader /packs/

ENTRYPOINT [ \
  "/packs/uploader" \
]
