# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ingress.proto

require 'google/protobuf'

require 'envelope_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "loggregator.v2.IngressResponse" do
  end
  add_message "loggregator.v2.BatchSenderResponse" do
  end
  add_message "loggregator.v2.SendResponse" do
  end
end

module Loggregator
  module V2
    IngressResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("loggregator.v2.IngressResponse").msgclass
    BatchSenderResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("loggregator.v2.BatchSenderResponse").msgclass
    SendResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("loggregator.v2.SendResponse").msgclass
  end
end
