// Code generated by counterfeiter. DO NOT EDIT.
package k8sfakes

import (
	"sync"

	"code.cloudfoundry.org/eirini/k8s"
	"code.cloudfoundry.org/eirini/opi"
	"k8s.io/api/core/v1"
)

type FakeLivenessProbeCreator struct {
	Stub        func(lrp *opi.LRP) *v1.Probe
	mutex       sync.RWMutex
	argsForCall []struct {
		lrp *opi.LRP
	}
	returns struct {
		result1 *v1.Probe
	}
	returnsOnCall map[int]struct {
		result1 *v1.Probe
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeLivenessProbeCreator) Spy(lrp *opi.LRP) *v1.Probe {
	fake.mutex.Lock()
	ret, specificReturn := fake.returnsOnCall[len(fake.argsForCall)]
	fake.argsForCall = append(fake.argsForCall, struct {
		lrp *opi.LRP
	}{lrp})
	fake.recordInvocation("LivenessProbeCreator", []interface{}{lrp})
	fake.mutex.Unlock()
	if fake.Stub != nil {
		return fake.Stub(lrp)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.returns.result1
}

func (fake *FakeLivenessProbeCreator) CallCount() int {
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	return len(fake.argsForCall)
}

func (fake *FakeLivenessProbeCreator) ArgsForCall(i int) *opi.LRP {
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	return fake.argsForCall[i].lrp
}

func (fake *FakeLivenessProbeCreator) Returns(result1 *v1.Probe) {
	fake.Stub = nil
	fake.returns = struct {
		result1 *v1.Probe
	}{result1}
}

func (fake *FakeLivenessProbeCreator) ReturnsOnCall(i int, result1 *v1.Probe) {
	fake.Stub = nil
	if fake.returnsOnCall == nil {
		fake.returnsOnCall = make(map[int]struct {
			result1 *v1.Probe
		})
	}
	fake.returnsOnCall[i] = struct {
		result1 *v1.Probe
	}{result1}
}

func (fake *FakeLivenessProbeCreator) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeLivenessProbeCreator) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ k8s.LivenessProbeCreator = new(FakeLivenessProbeCreator).Spy
