// Code generated by counterfeiter. DO NOT EDIT.
package k8sfakes

import (
	"sync"

	"code.cloudfoundry.org/eirini/k8s"
	"code.cloudfoundry.org/eirini/opi"
)

type FakeDeploymentManager struct {
	ListLRPsStub        func(namespace string) ([]opi.LRP, error)
	listLRPsMutex       sync.RWMutex
	listLRPsArgsForCall []struct {
		namespace string
	}
	listLRPsReturns struct {
		result1 []opi.LRP
		result2 error
	}
	listLRPsReturnsOnCall map[int]struct {
		result1 []opi.LRP
		result2 error
	}
	DeleteStub        func(appName, namespace string) error
	deleteMutex       sync.RWMutex
	deleteArgsForCall []struct {
		appName   string
		namespace string
	}
	deleteReturns struct {
		result1 error
	}
	deleteReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeDeploymentManager) ListLRPs(namespace string) ([]opi.LRP, error) {
	fake.listLRPsMutex.Lock()
	ret, specificReturn := fake.listLRPsReturnsOnCall[len(fake.listLRPsArgsForCall)]
	fake.listLRPsArgsForCall = append(fake.listLRPsArgsForCall, struct {
		namespace string
	}{namespace})
	fake.recordInvocation("ListLRPs", []interface{}{namespace})
	fake.listLRPsMutex.Unlock()
	if fake.ListLRPsStub != nil {
		return fake.ListLRPsStub(namespace)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.listLRPsReturns.result1, fake.listLRPsReturns.result2
}

func (fake *FakeDeploymentManager) ListLRPsCallCount() int {
	fake.listLRPsMutex.RLock()
	defer fake.listLRPsMutex.RUnlock()
	return len(fake.listLRPsArgsForCall)
}

func (fake *FakeDeploymentManager) ListLRPsArgsForCall(i int) string {
	fake.listLRPsMutex.RLock()
	defer fake.listLRPsMutex.RUnlock()
	return fake.listLRPsArgsForCall[i].namespace
}

func (fake *FakeDeploymentManager) ListLRPsReturns(result1 []opi.LRP, result2 error) {
	fake.ListLRPsStub = nil
	fake.listLRPsReturns = struct {
		result1 []opi.LRP
		result2 error
	}{result1, result2}
}

func (fake *FakeDeploymentManager) ListLRPsReturnsOnCall(i int, result1 []opi.LRP, result2 error) {
	fake.ListLRPsStub = nil
	if fake.listLRPsReturnsOnCall == nil {
		fake.listLRPsReturnsOnCall = make(map[int]struct {
			result1 []opi.LRP
			result2 error
		})
	}
	fake.listLRPsReturnsOnCall[i] = struct {
		result1 []opi.LRP
		result2 error
	}{result1, result2}
}

func (fake *FakeDeploymentManager) Delete(appName string, namespace string) error {
	fake.deleteMutex.Lock()
	ret, specificReturn := fake.deleteReturnsOnCall[len(fake.deleteArgsForCall)]
	fake.deleteArgsForCall = append(fake.deleteArgsForCall, struct {
		appName   string
		namespace string
	}{appName, namespace})
	fake.recordInvocation("Delete", []interface{}{appName, namespace})
	fake.deleteMutex.Unlock()
	if fake.DeleteStub != nil {
		return fake.DeleteStub(appName, namespace)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.deleteReturns.result1
}

func (fake *FakeDeploymentManager) DeleteCallCount() int {
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	return len(fake.deleteArgsForCall)
}

func (fake *FakeDeploymentManager) DeleteArgsForCall(i int) (string, string) {
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	return fake.deleteArgsForCall[i].appName, fake.deleteArgsForCall[i].namespace
}

func (fake *FakeDeploymentManager) DeleteReturns(result1 error) {
	fake.DeleteStub = nil
	fake.deleteReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeDeploymentManager) DeleteReturnsOnCall(i int, result1 error) {
	fake.DeleteStub = nil
	if fake.deleteReturnsOnCall == nil {
		fake.deleteReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeDeploymentManager) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.listLRPsMutex.RLock()
	defer fake.listLRPsMutex.RUnlock()
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeDeploymentManager) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ k8s.DeploymentManager = new(FakeDeploymentManager)
