#!/bin/bash

set -euo pipefail

export WIREMOCK_KEYSTORE_PASSWORD=${WIREMOCK_KEYSTORE_PASSWORD:-$(pass eirini/ci/wiremock-keystore-password)}
export CA_BUNDLE

main() {
  init_helm
  generate_secrets
  CA_BUNDLE="$(kubectl get secret -n eirini-core instance-index-env-injector-certs -o jsonpath="{.data['tls\.ca']}")"
  delete_migration_job
  skaffold $@
}

generate_secrets() {
  "$HOME/workspace/eirini-release/scripts/generate-secrets.sh" "*.eirini-core.svc" "$WIREMOCK_KEYSTORE_PASSWORD"
}

init_helm() {
  helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
  helm repo update
}

delete_migration_job() {
  kubectl -n eirini-core delete job eirini-app-migration || true
}

main $@
